spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fbs?useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '9191'

